import jsPDF from 'jspdf'

export interface BrandKitData {
  brandName: string
  tagline: string
  industry: string
  targetAudience: string
  pricePoint: string
  // Signal
  demandScore?: number
  competitionLevel?: string
  audienceHeat?: string
  marketGap?: string
  opportunityWindow?: string
  painPoints?: string[]
  // Craft
  brandVoice?: {
    tone?: string
    vibe?: string
    writing_example?: string
  }
  colorPalette?: { label: string; hex: string }[]
  typography?: { heading?: string; body?: string }
  productConcepts?: { name: string; price: string; desc: string }[]
  taglines?: string[]
}

const hexToRgb = (hex: string): [number, number, number] => {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex)
  return result
    ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)]
    : [255, 255, 255]
}

export const exportBrandKitPDF = (data: BrandKitData) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W = 210
  const margin = 20
  let y = 0

  // ── helpers ──────────────────────────────
  const fill = (r: number, g: number, b: number) => doc.setFillColor(r, g, b)
  const textCol = (r: number, g: number, b: number) => doc.setTextColor(r, g, b)
  const rect = (x: number, yy: number, w: number, h: number) =>
    doc.rect(x, yy, w, h, 'F')

  const sectionLabel = (label: string, yPos: number) => {
    textCol(255, 100, 0)
    doc.setFontSize(7)
    doc.setFont('helvetica', 'bold')
    doc.text(label.toUpperCase(), margin, yPos)
    fill(255, 100, 0)
    rect(margin, yPos + 1.5, 20, 0.5)
  }

  const bodyText = (text: string, x: number, yy: number, maxWidth = 170) => {
    textCol(180, 180, 180)
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(text, maxWidth)
    doc.text(lines, x, yy)
    return lines.length * 4.5
  }

  // ── PAGE 1 — Cover ────────────────────────
  fill(5, 5, 5)
  rect(0, 0, W, 297)

  // Orange accent bar top
  fill(255, 100, 0)
  rect(0, 0, W, 2)

  // FORGE wordmark
  textCol(255, 255, 255)
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.text('FORGE', margin, 18)
  textCol(120, 120, 120)
  doc.setFontSize(7)
  doc.setFont('helvetica', 'normal')
  doc.text('AI BRAND OS', margin + 16, 18)

  // Brand name — large
  textCol(255, 255, 255)
  doc.setFontSize(42)
  doc.setFont('helvetica', 'bold')
  doc.text(data.brandName.toUpperCase(), margin, 100)

  // Tagline
  textCol(255, 100, 0)
  doc.setFontSize(13)
  doc.setFont('helvetica', 'normal')
  doc.text(`"${data.tagline}"`, margin, 115)

  // Meta pills
  const pills = [data.industry, data.targetAudience, data.pricePoint].filter(Boolean)
  let pillX = margin
  pills.forEach((pill) => {
    if (!pill) return
    fill(30, 30, 30)
    const tw = doc.getTextWidth(pill!) + 8
    rect(pillX, 125, tw, 7)
    textCol(200, 200, 200)
    doc.setFontSize(7)
    doc.text(pill!, pillX + 4, 130.5)
    pillX += tw + 4
  })

  // Divider
  fill(40, 40, 40)
  rect(margin, 140, W - margin * 2, 0.5)

  // Signal scores row
  if (data.demandScore !== undefined) {
    const metrics = [
      { label: 'Demand Score', value: `${data.demandScore}/100` },
      { label: 'Competition', value: data.competitionLevel || '—' },
      { label: 'Audience Heat', value: data.audienceHeat || '—' },
    ]
    metrics.forEach((m, i) => {
      const mx = margin + i * 57
      textCol(255, 100, 0)
      doc.setFontSize(20)
      doc.setFont('helvetica', 'bold')
      doc.text(m.value, mx, 162)
      textCol(100, 100, 100)
      doc.setFontSize(7)
      doc.setFont('helvetica', 'normal')
      doc.text(m.label.toUpperCase(), mx, 168)
    })
  }

  // Opportunity window
  if (data.opportunityWindow) {
    fill(20, 20, 20)
    rect(margin, 178, W - margin * 2, 20)
    textCol(255, 100, 0)
    doc.setFontSize(7)
    doc.setFont('helvetica', 'bold')
    doc.text('OPPORTUNITY WINDOW', margin + 4, 185)
    textCol(200, 200, 200)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(data.opportunityWindow, W - margin * 2 - 10)
    doc.text(lines.slice(0, 2), margin + 4, 191)
  }

  // Bottom bar
  fill(15, 15, 15)
  rect(0, 275, W, 22)
  textCol(80, 80, 80)
  doc.setFontSize(7)
  doc.text('CONFIDENTIAL BRAND KIT — GENERATED BY FORGE AI', margin, 285)
  textCol(80, 80, 80)
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  doc.text(dateStr, W - margin - doc.getTextWidth(dateStr), 285)

  // ── PAGE 2 — Brand Identity ──────────────
  doc.addPage()
  fill(5, 5, 5)
  rect(0, 0, W, 297)
  fill(255, 100, 0)
  rect(0, 0, W, 2)

  y = 20
  textCol(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('Brand Identity', margin, y)
  y += 14

  // Color palette
  if (data.colorPalette && data.colorPalette.length > 0) {
    sectionLabel('Color Palette', y)
    y += 8
    data.colorPalette.slice(0, 5).forEach((color, i) => {
      const rgb = hexToRgb(color.hex)
      fill(rgb[0], rgb[1], rgb[2])
      rect(margin + i * 36, y, 28, 16)
      textCol(180, 180, 180)
      doc.setFontSize(7)
      doc.setFont('helvetica', 'bold')
      doc.text(color.hex.toUpperCase(), margin + i * 36, y + 22)
      doc.setFont('helvetica', 'normal')
      doc.text(color.label, margin + i * 36, y + 27)
    })
    y += 34
  }

  // Typography
  if (data.typography) {
    sectionLabel('Typography', y)
    y += 8
    fill(20, 20, 20)
    rect(margin, y, (W - margin * 2) / 2 - 4, 18)
    textCol(255, 100, 0)
    doc.setFontSize(7)
    doc.text('HEADING', margin + 4, y + 6)
    textCol(255, 255, 255)
    doc.setFontSize(10)
    doc.text(data.typography.heading || 'Inter Bold', margin + 4, y + 14)

    fill(20, 20, 20)
    const bx = margin + (W - margin * 2) / 2 + 4
    rect(bx, y, (W - margin * 2) / 2 - 4, 18)
    textCol(255, 100, 0)
    doc.setFontSize(7)
    doc.text('BODY', bx + 4, y + 6)
    textCol(255, 255, 255)
    doc.setFontSize(10)
    doc.text(data.typography.body || 'Inter Regular', bx + 4, y + 14)
    y += 26
  }

  // Brand Voice
  if (data.brandVoice) {
    sectionLabel('Brand Voice', y)
    y += 8
    const voiceItems = [
      { label: 'Tone', value: data.brandVoice.tone },
      { label: 'Vibe', value: data.brandVoice.vibe },
      { label: 'Writing Example', value: data.brandVoice.writing_example },
    ].filter(v => v.value)

    voiceItems.forEach((item) => {
      fill(18, 18, 18)
      rect(margin, y, W - margin * 2, 14)
      textCol(255, 100, 0)
      doc.setFontSize(7)
      doc.setFont('helvetica', 'bold')
      doc.text(item.label!.toUpperCase(), margin + 4, y + 6)
      textCol(200, 200, 200)
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      const lines = doc.splitTextToSize(item.value!, W - margin * 2 - 50)
      doc.text(lines[0], margin + 35, y + 6)
      y += 17
    })
    y += 4
  }

  // Taglines
  if (data.taglines && data.taglines.length > 0) {
    sectionLabel('Taglines', y)
    y += 8
    data.taglines.slice(0, 4).forEach((tl) => {
      fill(12, 12, 12)
      rect(margin, y, W - margin * 2, 10)
      fill(255, 100, 0)
      rect(margin, y, 2, 10)
      textCol(220, 220, 220)
      doc.setFontSize(8)
      doc.text(`"${tl}"`, margin + 6, y + 7)
      y += 13
    })
    y += 4
  }

  // Pain points
  if (data.painPoints && data.painPoints.length > 0) {
    sectionLabel('Audience Pain Points', y)
    y += 8
    data.painPoints.slice(0, 4).forEach((pp) => {
      textCol(160, 160, 160)
      doc.setFontSize(8)
      doc.text('•', margin, y)
      const lines = doc.splitTextToSize(pp, W - margin * 2 - 8)
      doc.text(lines, margin + 5, y)
      y += lines.length * 5 + 2
    })
  }

  // ── PAGE 3 — Products ────────────────────
  if (data.productConcepts && data.productConcepts.length > 0) {
    doc.addPage()
    fill(5, 5, 5)
    rect(0, 0, W, 297)
    fill(255, 100, 0)
    rect(0, 0, W, 2)

    y = 20
    textCol(255, 255, 255)
    doc.setFontSize(22)
    doc.setFont('helvetica', 'bold')
    doc.text('Product Line', margin, y)
    y += 14

    data.productConcepts.slice(0, 6).forEach((product, i) => {
      fill(i === 0 ? 20 : 15, i === 0 ? 20 : 15, i === 0 ? 20 : 15)
      rect(margin, y, W - margin * 2, 26)
      if (i === 0) {
        fill(255, 100, 0)
        rect(margin, y, 2, 26)
      }
      textCol(255, 255, 255)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.text(product.name, margin + 6, y + 9)
      textCol(255, 100, 0)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'bold')
      doc.text(product.price, W - margin - doc.getTextWidth(product.price), y + 9)
      textCol(150, 150, 150)
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      const lines = doc.splitTextToSize(product.desc, W - margin * 2 - 12)
      doc.text(lines.slice(0, 2), margin + 6, y + 17)
      y += 30
    })
  }

  // Market Gap — last page or append
  if (data.marketGap) {
    y += 10
    if (y > 240) {
      doc.addPage()
      fill(5, 5, 5)
      rect(0, 0, W, 297)
      fill(255, 100, 0)
      rect(0, 0, W, 2)
      y = 30
    }
    sectionLabel('Market Opportunity', y)
    y += 8
    fill(15, 20, 15)
    rect(margin, y, W - margin * 2, 32)
    fill(0, 180, 80)
    rect(margin, y, 2, 32)
    textCol(180, 220, 180)
    doc.setFontSize(8)
    const lines = doc.splitTextToSize(data.marketGap, W - margin * 2 - 10)
    doc.text(lines.slice(0, 5), margin + 6, y + 8)
  }

  doc.save(`${data.brandName.replace(/\s+/g, '-').toLowerCase()}-brand-kit.pdf`)
}
